--------------------------------------------------------
-- Archivo creado  - viernes-mayo-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENCIAS
--------------------------------------------------------

  CREATE TABLE "RENTACAR"."AGENCIAS" 
   (	"COD_AGENCIA" VARCHAR2(10 BYTE), 
	"NOMBRE_AGENCIA" VARCHAR2(100 BYTE), 
	"TELEFONO_AGENCIA" VARCHAR2(20 BYTE), 
	"EMAIL_AGENCIA" VARCHAR2(100 BYTE), 
	"UBICACION_AGENCIA" VARCHAR2(100 BYTE), 
	"HORARIO_AGENCIA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "RENTACAR"."CLIENTES" 
   (	"CED_CLIENTE" VARCHAR2(20 BYTE), 
	"NOMBRE_CLIENTE" VARCHAR2(100 BYTE), 
	"TELEFONO_CLIENTE" VARCHAR2(20 BYTE), 
	"EMAIL_CLIENTE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Table MARCA_VEHICULO
--------------------------------------------------------

  CREATE TABLE "RENTACAR"."MARCA_VEHICULO" 
   (	"COD_MARCA_VEHICULO" VARCHAR2(10 BYTE), 
	"DESCRIPCION_MARCA_VEHICULO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Table RESERVAS
--------------------------------------------------------

  CREATE TABLE "RENTACAR"."RESERVAS" 
   (	"COD_RESERVA" VARCHAR2(10 BYTE), 
	"CODIGO_AGENCIA" VARCHAR2(10 BYTE), 
	"CEDULA_CLIENTE" VARCHAR2(10 BYTE), 
	"CODIGO_VEHICULO" VARCHAR2(10 BYTE), 
	"FECHA_INICIO" DATE, 
	"FECHA_FINAL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "RENTACAR"."ROLES" 
   (	"COD_ROL" VARCHAR2(10 BYTE), 
	"DESCRIPCION_ROL" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Table TIPO_TRANSMISION
--------------------------------------------------------

  CREATE TABLE "RENTACAR"."TIPO_TRANSMISION" 
   (	"COD_TIPO_TRANSMISION" VARCHAR2(10 BYTE), 
	"DESCRIPCION_TIPO_TRANSMISION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Table TIPO_VEHICULO
--------------------------------------------------------

  CREATE TABLE "RENTACAR"."TIPO_VEHICULO" 
   (	"COD_TIPO_VEHICULO" VARCHAR2(10 BYTE), 
	"DESCRIPCION_TIPO_VEHICULO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "RENTACAR"."USUARIOS" 
   (	"NOMBRE_USUARIO" VARCHAR2(20 BYTE), 
	"CLAVE_USUARIO" VARCHAR2(25 BYTE), 
	"CODIGO_ROL" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Table VEHICULOS
--------------------------------------------------------

  CREATE TABLE "RENTACAR"."VEHICULOS" 
   (	"COD_VEHICULO" VARCHAR2(10 BYTE), 
	"CODIGO_TIPO_VEHICULO" VARCHAR2(10 BYTE), 
	"CODIGO_TIPO_TRANSMISION" VARCHAR2(10 BYTE), 
	"CODIGO_MARCA_VEHICULO" VARCHAR2(10 BYTE), 
	"CAPACIDAD_VEHICULO" NUMBER, 
	"PLACA_VEHICULO" VARCHAR2(15 BYTE), 
	"DESCRIPCION_VEHICULO" VARCHAR2(150 BYTE), 
	"PRECIO_VEHICULO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
REM INSERTING into RENTACAR.AGENCIAS
SET DEFINE OFF;
Insert into RENTACAR.AGENCIAS (COD_AGENCIA,NOMBRE_AGENCIA,TELEFONO_AGENCIA,EMAIL_AGENCIA,UBICACION_AGENCIA,HORARIO_AGENCIA) values ('AG-7','Agencia Puntarenas ','65987423','puntarenasrent@gmail.com','Puntarenas Centro','7 am-3 pm');
Insert into RENTACAR.AGENCIAS (COD_AGENCIA,NOMBRE_AGENCIA,TELEFONO_AGENCIA,EMAIL_AGENCIA,UBICACION_AGENCIA,HORARIO_AGENCIA) values ('AG-5','Agencia Cartago','85632145','cartagorent@gmail.com','Cartago Centro','5 am-3 pm');
Insert into RENTACAR.AGENCIAS (COD_AGENCIA,NOMBRE_AGENCIA,TELEFONO_AGENCIA,EMAIL_AGENCIA,UBICACION_AGENCIA,HORARIO_AGENCIA) values ('AG-10','Agencia Tres Rios','24307739','agenciatresrios@gmail.com','Cartago ','Lun-Vie 8 a 4:30');
REM INSERTING into RENTACAR.CLIENTES
SET DEFINE OFF;
Insert into RENTACAR.CLIENTES (CED_CLIENTE,NOMBRE_CLIENTE,TELEFONO_CLIENTE,EMAIL_CLIENTE) values ('207680215','David','62663545','davidlml@gmail.com');
Insert into RENTACAR.CLIENTES (CED_CLIENTE,NOMBRE_CLIENTE,TELEFONO_CLIENTE,EMAIL_CLIENTE) values ('207680218','Jesus Guzman','60134556','jesus@gmail.com');
Insert into RENTACAR.CLIENTES (CED_CLIENTE,NOMBRE_CLIENTE,TELEFONO_CLIENTE,EMAIL_CLIENTE) values ('209770549','Manuel Diaz Perez ','65412398','xxxdarsxxx0@gmail.com');
Insert into RENTACAR.CLIENTES (CED_CLIENTE,NOMBRE_CLIENTE,TELEFONO_CLIENTE,EMAIL_CLIENTE) values ('207690712','Jesus Gonzalez  Perez ','85630942','jesugo@gmail.com');
REM INSERTING into RENTACAR.MARCA_VEHICULO
SET DEFINE OFF;
Insert into RENTACAR.MARCA_VEHICULO (COD_MARCA_VEHICULO,DESCRIPCION_MARCA_VEHICULO) values ('M-1','Toyota');
Insert into RENTACAR.MARCA_VEHICULO (COD_MARCA_VEHICULO,DESCRIPCION_MARCA_VEHICULO) values ('M-2','Nissan');
REM INSERTING into RENTACAR.RESERVAS
SET DEFINE OFF;
REM INSERTING into RENTACAR.ROLES
SET DEFINE OFF;
REM INSERTING into RENTACAR.TIPO_TRANSMISION
SET DEFINE OFF;
Insert into RENTACAR.TIPO_TRANSMISION (COD_TIPO_TRANSMISION,DESCRIPCION_TIPO_TRANSMISION) values ('TT-1','Automatico');
Insert into RENTACAR.TIPO_TRANSMISION (COD_TIPO_TRANSMISION,DESCRIPCION_TIPO_TRANSMISION) values ('TT-2','Manual');
REM INSERTING into RENTACAR.TIPO_VEHICULO
SET DEFINE OFF;
Insert into RENTACAR.TIPO_VEHICULO (COD_TIPO_VEHICULO,DESCRIPCION_TIPO_VEHICULO) values ('TV-1','Automovil');
Insert into RENTACAR.TIPO_VEHICULO (COD_TIPO_VEHICULO,DESCRIPCION_TIPO_VEHICULO) values ('TV-2','4x4');
REM INSERTING into RENTACAR.USUARIOS
SET DEFINE OFF;
REM INSERTING into RENTACAR.VEHICULOS
SET DEFINE OFF;
Insert into RENTACAR.VEHICULOS (COD_VEHICULO,CODIGO_TIPO_VEHICULO,CODIGO_TIPO_TRANSMISION,CODIGO_MARCA_VEHICULO,CAPACIDAD_VEHICULO,PLACA_VEHICULO,DESCRIPCION_VEHICULO,PRECIO_VEHICULO) values ('A-2','TV-1','TT-1','M-2','5','789654','prueba','20000');
Insert into RENTACAR.VEHICULOS (COD_VEHICULO,CODIGO_TIPO_VEHICULO,CODIGO_TIPO_TRANSMISION,CODIGO_MARCA_VEHICULO,CAPACIDAD_VEHICULO,PLACA_VEHICULO,DESCRIPCION_VEHICULO,PRECIO_VEHICULO) values ('A-1','TV-1','TT-1','M-1','5','564987','Vhiculo toyota automatico, 4 puertas','30000');
--------------------------------------------------------
--  DDL for Index PK_MARCA_VEHICULO
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENTACAR"."PK_MARCA_VEHICULO" ON "RENTACAR"."MARCA_VEHICULO" ("COD_MARCA_VEHICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Index PK_VEHICULO
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENTACAR"."PK_VEHICULO" ON "RENTACAR"."VEHICULOS" ("COD_VEHICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENTACAR"."PK_CLIENTE" ON "RENTACAR"."CLIENTES" ("CED_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Index PK_TIPO_VEHICULO
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENTACAR"."PK_TIPO_VEHICULO" ON "RENTACAR"."TIPO_VEHICULO" ("COD_TIPO_VEHICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Index PK_ROL
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENTACAR"."PK_ROL" ON "RENTACAR"."ROLES" ("COD_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENTACAR"."PK_USUARIO" ON "RENTACAR"."USUARIOS" ("NOMBRE_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Index PK_TIPO_TRANSMISION
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENTACAR"."PK_TIPO_TRANSMISION" ON "RENTACAR"."TIPO_TRANSMISION" ("COD_TIPO_TRANSMISION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Index PK_AGENCIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENTACAR"."PK_AGENCIA" ON "RENTACAR"."AGENCIAS" ("COD_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Index PK_RESERVA
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENTACAR"."PK_RESERVA" ON "RENTACAR"."RESERVAS" ("COD_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB" ;
--------------------------------------------------------
--  DDL for Procedure ELIMINARAGENCIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RENTACAR"."ELIMINARAGENCIA" (codigoin IN AGENCIAS.COD_AGENCIA%TYPE)
as
begin
    delete from AGENCIAS where COD_AGENCIA=codigoin;
end;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARCLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RENTACAR"."ELIMINARCLIENTE" (cedulain IN CLIENTES.CED_CLIENTE%TYPE)
as
begin
    delete from CLIENTES where CED_CLIENTE=cedulain;
end;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARVEHICULO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RENTACAR"."ELIMINARVEHICULO" (codigoin IN VEHICULOS.COD_VEHICULO%TYPE)
as
begin
    delete from VEHICULOS where COD_VEHICULO=codigoin;
end;

/
--------------------------------------------------------
--  DDL for Procedure INSERTARAGENCIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RENTACAR"."INSERTARAGENCIA" (codigo IN AGENCIAS.COD_AGENCIA%TYPE,nombre IN AGENCIAS.NOMBRE_AGENCIA%TYPE,telefono IN AGENCIAS.TELEFONO_AGENCIA%TYPE,
email IN AGENCIAS.EMAIL_AGENCIA%TYPE,ubicacion IN AGENCIAS.UBICACION_AGENCIA%TYPE,horario IN AGENCIAS.HORARIO_AGENCIA%TYPE)
AS
BEGIN
	INSERT INTO AGENCIAS VALUES(codigo,nombre,telefono,email,ubicacion,horario);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERTARCLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RENTACAR"."INSERTARCLIENTE" (cedula IN CLIENTES.CED_CLIENTE%TYPE,nombre IN CLIENTES.NOMBRE_CLIENTE%TYPE,telefono IN CLIENTES.TELEFONO_CLIENTE%TYPE,
email IN CLIENTES.EMAIL_CLIENTE%TYPE)
AS
BEGIN
	INSERT INTO CLIENTES VALUES(cedula,nombre,telefono,email);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERTARVEHICULO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RENTACAR"."INSERTARVEHICULO" (codigo IN VEHICULOS.COD_VEHICULO%TYPE,tipo IN VEHICULOS.CODIGO_TIPO_VEHICULO%TYPE,
transmision IN VEHICULOS.CODIGO_TIPO_TRANSMISION%TYPE,marca IN VEHICULOS.CODIGO_MARCA_VEHICULO%TYPE,capacidad IN VEHICULOS.CAPACIDAD_VEHICULO%TYPE,
placa IN VEHICULOS.PLACA_VEHICULO%TYPE, descripcion IN VEHICULOS.DESCRIPCION_VEHICULO%TYPE,precio IN VEHICULOS.PRECIO_VEHICULO%TYPE)
AS
BEGIN
	INSERT INTO VEHICULOS VALUES(codigo,tipo,transmision,marca,capacidad,placa,descripcion,precio);
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARAGENCIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RENTACAR"."MODIFICARAGENCIA" (codigoin IN AGENCIAS.COD_AGENCIA%TYPE,nombrein IN AGENCIAS.NOMBRE_AGENCIA%TYPE,telefonoin IN AGENCIAS.TELEFONO_AGENCIA%TYPE,
emailin IN AGENCIAS.EMAIL_AGENCIA%TYPE,ubicacionin IN AGENCIAS.UBICACION_AGENCIA%TYPE,horarioin IN AGENCIAS.HORARIO_AGENCIA%TYPE)
AS
BEGIN
UPDATE AGENCIAS SET NOMBRE_AGENCIA=nombrein,TELEFONO_AGENCIA=telefonoin,EMAIL_AGENCIA=emailin,UBICACION_AGENCIA=ubicacionin, HORARIO_AGENCIA=horarioin WHERE COD_AGENCIA=codigoin;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARCLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RENTACAR"."MODIFICARCLIENTE" (cedulain IN CLIENTES.CED_CLIENTE%TYPE,nombrein IN CLIENTES.NOMBRE_CLIENTE%TYPE,telefonoin IN CLIENTES.TELEFONO_CLIENTE%TYPE,
emailin IN CLIENTES.EMAIL_CLIENTE%TYPE)
AS
BEGIN
UPDATE CLIENTES SET NOMBRE_CLIENTE=nombrein,TELEFONO_CLIENTE=telefonoin,EMAIL_CLIENTE=emailin WHERE CED_CLIENTE=cedulain;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARVEHICULO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RENTACAR"."MODIFICARVEHICULO" (codigoin IN VEHICULOS.COD_VEHICULO%TYPE,tipoin IN VEHICULOS.CODIGO_TIPO_VEHICULO%TYPE,
transmisionin IN VEHICULOS.CODIGO_TIPO_TRANSMISION%TYPE,marcain IN VEHICULOS.CODIGO_MARCA_VEHICULO%TYPE,capacidadin IN VEHICULOS.CAPACIDAD_VEHICULO%TYPE,
placain IN VEHICULOS.PLACA_VEHICULO%TYPE, descripcionin IN VEHICULOS.DESCRIPCION_VEHICULO%TYPE,precioin IN VEHICULOS.PRECIO_VEHICULO%TYPE)
AS
BEGIN
UPDATE VEHICULOS SET CODIGO_TIPO_VEHICULO = tipoin, CODIGO_TIPO_TRANSMISION = transmisionin, CODIGO_MARCA_VEHICULO = marcain,
CAPACIDAD_VEHICULO = capacidadin,PLACA_VEHICULO = placain, DESCRIPCION_VEHICULO = descripcionin, PRECIO_VEHICULO = precioin
WHERE COD_VEHICULO=codigoin;
END;

/
--------------------------------------------------------
--  DDL for Package TYPES
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "RENTACAR"."TYPES" 
AS
     TYPE ref_cursor IS REF CURSOR;
END;

/
--------------------------------------------------------
--  DDL for Function BUSCARCLIENTECEDULA
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "RENTACAR"."BUSCARCLIENTECEDULA" (cedulaBuscar IN CLIENTES.CED_CLIENTE%TYPE)
RETURN Types.ref_cursor 
AS 
        cliente_cursor types.ref_cursor; 
BEGIN 
  OPEN cliente_cursor FOR 
       SELECT CED_CLIENTE,NOMBRE_CLIENTE,TELEFONO_CLIENTE,EMAIL_CLIENTE FROM CLIENTES WHERE CED_CLIENTE LIKE cedulaBuscar||'%'; 
RETURN cliente_cursor; 
END;

/
--------------------------------------------------------
--  DDL for Function LISTARAGENCIAS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "RENTACAR"."LISTARAGENCIAS" 
RETURN Types.ref_cursor 
AS 
       agencia_cursor types.ref_cursor; 
BEGIN 
  OPEN agencia_cursor FOR 
       SELECT COD_AGENCIA,NOMBRE_AGENCIA,TELEFONO_AGENCIA,EMAIL_AGENCIA,UBICACION_AGENCIA,HORARIO_AGENCIA from AGENCIAS; 
RETURN agencia_cursor; 
END;

/
--------------------------------------------------------
--  DDL for Function LISTARCLIENTES
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "RENTACAR"."LISTARCLIENTES" 
RETURN Types.ref_cursor 
AS 
       cliente_cursor types.ref_cursor; 
BEGIN 
  OPEN cliente_cursor FOR 
       SELECT CED_CLIENTE,NOMBRE_CLIENTE,TELEFONO_CLIENTE,EMAIL_CLIENTE from CLIENTES; 
RETURN cliente_cursor; 
END;

/
--------------------------------------------------------
--  DDL for Function LISTARMARCAVEHICULOS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "RENTACAR"."LISTARMARCAVEHICULOS" 
RETURN Types.ref_cursor 
AS 
       marca_vehiculo_cursor types.ref_cursor; 
BEGIN 
  OPEN marca_vehiculo_cursor FOR 
       SELECT COD_MARCA_VEHICULO,DESCRIPCION_MARCA_VEHICULO FROM MARCA_VEHICULO;
RETURN marca_vehiculo_cursor; 
END;

/
--------------------------------------------------------
--  DDL for Function LISTARTIPOTRANSMISIONVEHICULOS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "RENTACAR"."LISTARTIPOTRANSMISIONVEHICULOS" 
RETURN Types.ref_cursor 
AS 
       tipo_transmision_cursor types.ref_cursor; 
BEGIN 
  OPEN tipo_transmision_cursor FOR 
       SELECT COD_TIPO_TRANSMISION,DESCRIPCION_TIPO_TRANSMISION FROM TIPO_TRANSMISION;
RETURN tipo_transmision_cursor; 
END;

/
--------------------------------------------------------
--  DDL for Function LISTARTIPOVEHICULOS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "RENTACAR"."LISTARTIPOVEHICULOS" 
RETURN Types.ref_cursor 
AS 
       tipo_vehiculo_cursor types.ref_cursor; 
BEGIN 
  OPEN tipo_vehiculo_cursor FOR 
       SELECT COD_TIPO_VEHICULO,DESCRIPCION_TIPO_VEHICULO FROM TIPO_VEHICULO;
RETURN tipo_vehiculo_cursor; 
END;

/
--------------------------------------------------------
--  DDL for Function LISTARVEHICULOS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "RENTACAR"."LISTARVEHICULOS" 
RETURN Types.ref_cursor 
AS 
       vehiculo_cursor types.ref_cursor; 
BEGIN 
  OPEN vehiculo_cursor FOR 
       SELECT V.COD_VEHICULO,V.CODIGO_TIPO_VEHICULO,V.CODIGO_TIPO_TRANSMISION,V.CODIGO_MARCA_VEHICULO,V.CAPACIDAD_VEHICULO,V.PLACA_VEHICULO,V.DESCRIPCION_VEHICULO,
       V.PRECIO_VEHICULO, TV.COD_TIPO_VEHICULO, TT.COD_TIPO_TRANSMISION,MV.COD_MARCA_VEHICULO 
       FROM VEHICULOS V INNER JOIN TIPO_VEHICULO TV ON V.CODIGO_TIPO_VEHICULO = TV.COD_TIPO_VEHICULO
                        INNER JOIN TIPO_TRANSMISION TT ON V.CODIGO_TIPO_TRANSMISION = TT.COD_TIPO_TRANSMISION
                        INNER JOIN MARCA_VEHICULO MV ON V.CODIGO_MARCA_VEHICULO = MV.COD_MARCA_VEHICULO;
RETURN vehiculo_cursor; 
END;

/
--------------------------------------------------------
--  Constraints for Table TIPO_TRANSMISION
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."TIPO_TRANSMISION" ADD CONSTRAINT "PK_TIPO_TRANSMISION" PRIMARY KEY ("COD_TIPO_TRANSMISION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVAS
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."RESERVAS" ADD CONSTRAINT "PK_RESERVAS" PRIMARY KEY ("COD_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MARCA_VEHICULO
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."MARCA_VEHICULO" ADD CONSTRAINT "PK_MARCA_VEHICULO" PRIMARY KEY ("COD_MARCA_VEHICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."CLIENTES" ADD CONSTRAINT "PK_CLIENTE" PRIMARY KEY ("CED_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VEHICULOS
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."VEHICULOS" ADD CONSTRAINT "PK_VEHICULO" PRIMARY KEY ("COD_VEHICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_VEHICULO
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."TIPO_VEHICULO" ADD CONSTRAINT "PK_TIPO_VEHICULO" PRIMARY KEY ("COD_TIPO_VEHICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."USUARIOS" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("NOMBRE_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AGENCIAS
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."AGENCIAS" ADD CONSTRAINT "PK_AGENCIA" PRIMARY KEY ("COD_AGENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."ROLES" ADD CONSTRAINT "PK_ROL" PRIMARY KEY ("COD_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RENTACARDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVAS
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."RESERVAS" ADD CONSTRAINT "FK_RESERVA_AGENCIA" FOREIGN KEY ("CODIGO_AGENCIA")
	  REFERENCES "RENTACAR"."AGENCIAS" ("COD_AGENCIA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RENTACAR"."RESERVAS" ADD CONSTRAINT "FK_RESERVA_CLIENTE" FOREIGN KEY ("CEDULA_CLIENTE")
	  REFERENCES "RENTACAR"."CLIENTES" ("CED_CLIENTE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RENTACAR"."RESERVAS" ADD CONSTRAINT "FK_RESERVA_VEHICULO" FOREIGN KEY ("CODIGO_VEHICULO")
	  REFERENCES "RENTACAR"."VEHICULOS" ("COD_VEHICULO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."USUARIOS" ADD CONSTRAINT "FK_USUARIO_ROL" FOREIGN KEY ("CODIGO_ROL")
	  REFERENCES "RENTACAR"."ROLES" ("COD_ROL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICULOS
--------------------------------------------------------

  ALTER TABLE "RENTACAR"."VEHICULOS" ADD CONSTRAINT "FK_VEHICULO_MARCAVEHICULO" FOREIGN KEY ("CODIGO_MARCA_VEHICULO")
	  REFERENCES "RENTACAR"."MARCA_VEHICULO" ("COD_MARCA_VEHICULO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RENTACAR"."VEHICULOS" ADD CONSTRAINT "FK_VEHICULO_TIPOTRANSMISION" FOREIGN KEY ("CODIGO_TIPO_TRANSMISION")
	  REFERENCES "RENTACAR"."TIPO_TRANSMISION" ("COD_TIPO_TRANSMISION") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RENTACAR"."VEHICULOS" ADD CONSTRAINT "FK_VEHICULO_TIPOVEHICULO" FOREIGN KEY ("CODIGO_TIPO_VEHICULO")
	  REFERENCES "RENTACAR"."TIPO_VEHICULO" ("COD_TIPO_VEHICULO") ON DELETE CASCADE ENABLE;
